### ISSUE TITLE
Expose compose function

### ISSUE THREAD

**Issue by codedavinci** [markerikson/redux-starter-kit#26]
Having in mind that there's a `redux` dependency in the project and the `combineReducers` is being exposed, I believe we should also expose the`compose` function.

Reason: 
* People would not `npm install` it
* Double `import redux` just to consume one function.
* To make it more complete, as it's a such a nice helper to have under your sleeve.

**Comment by nickmccurdy** [comment]
As I mentioned elsewhere, I think I'd rather not re-export anything from Redux, but I think this is a great idea for now since it's probably the second most commonly used utility function in Redux along with compose, and exposing it also feels more consistent.

**Comment by nickmccurdy** [comment]
Forgot to close this, the PR was merged! Thanks @codedavinci
