### ISSUE TITLE
Enable Redux devtools by default

### ISSUE THREAD

**Issue by nickmccurdy** [markerikson/redux-starter-kit#3]
Unlike a production build of something like React that has much more overhead for developer tooling, Redux devtools has very little overhead especially because it's mostly disabled until the Redux developer tools extension is open. I think it would be best to keep this on by default, but allow users 
 to manually set it to `NODE_ENV !== production` if it's necessary for some reason. 

https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f

**Comment by markerikson** [comment]
Yeah, I'm good with that idea.  PR?
