### ISSUE TITLE
Some exports are undefined in create-react-app

### ISSUE THREAD

**Issue by nickmccurdy** [markerikson/redux-starter-kit#6]
All the code examples are used in `src/index.js` as generated by `create-react-app`.

## Undefined

```js
import redux from "@acemarke/redux-starter-kit";
import {createReducer} from "@acemarke/redux-starter-kit";
```

## Defined
```js
import {configureStore} from "@acemarke/redux-starter-kit";
import {createSelector} from "@acemarke/redux-starter-kit";
import {createNextState} from "@acemarke/redux-starter-kit";
import {combineReducers} from "@acemarke/redux-starter-kit";
import {createDefaultMiddleware} from "@acemarke/redux-starter-kit";
```

**Comment by nickmccurdy** [comment]
I'm still looking into this, it seems like we just forgot to export `createReducer` and there isn't meant to be a default export.

**Comment by markerikson** [comment]
Oops :)

Can you PR that real fast, please?

**Comment by nickmccurdy** [comment]
Sure, I'm planning some related changes like adding `combineReducers` and `createDefaultMiddleware` to the readme. Should I also reexport everything else in `redux` or do you want to leave it as just `combineReducers` for now?

**Comment by markerikson** [comment]
Let's just re-export `combineReducers`.

**Comment by rabidpug** [comment]
Hi,

I'm getting undefined when importing createReducer using NPM package v0.0.5. Did this fix not get included in the release?

**Comment by markerikson** [comment]
Y'know, it would probably help if I actually _re-built the package_ before publishing it...

**Comment by markerikson** [comment]
Just rebuilt and published 0.0.6.  Try that and let me know if it works.

Apologies for the inconvenience.  This is literally the first NPM package I've ever published, and also it's something I basically threw together in an afternoon.  There's a reason why I haven't even marked it as 0.1.0 yet...

**Comment by nickmccurdy** [comment]
No worries. It would probably help to automate more of the publishing, mainly adding the build command to the `prepare` script which automatically gets run after installation and publishing.

**Comment by rabidpug** [comment]
It's working great now, thanks!
